# These are supported funding model platforms

github: ckdash-git # Replace with your GitHub username
buy_me_a_coffee: ckdash # Replace with your Buy Me a Coffee username
custom: ["https://buymeacoffee.com/ckdash"]